#!/bin/sh

installer='pmx-agent-latest.tar.gz'
destination=~/pmx-agent
curl -O "http://download.panamax.io/agent/$installer"
mkdir -p ${destination} && tar -C ${destination} -zxvf ${installer}
sudo ln -sf "$destination"/pmx-agent /usr/local/bin/pmx-agent
pmx-agent
